
name: Create Blender addon .zip file

on:
  push:
   branches:
    - release
  pull_request:
   branches:
    - release

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: 
            ${{ github.workspace }}
          dest: blenderbim_spreadsheet.zip
      - uses: actions/upload-artifact@v1
        with:
          name: blenderbim-spreadsheet
          path: blenderbim_spreadsheet.zip