
name: Create Blender addon .zip file

on:
  push:
   branches:
    - master
  pull_request:
   branches:
    - master

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create ZIP file
        run: |
          zip -r blenderbim_spreadsheet libs __init__.py operator.py prop.py ui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: blenderbim_spreadsheet.zip
          path: blenderbim_spreadsheet
          