
name: Create Blender addon .zip file

on:
  push:
   branches:
    - master
  pull_request:
   branches:
    - master

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: 
            - libs/
            - __init__.py
            - operator.py
            - prop.py
            - ui.py
          dest: blenderbim_spreadsheet.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
